port: 8080

database:
    port: 5444
    name: beppin
    user: beppin
    password: 99b72ca2a166e5f6b0a99e7bd788a6e158130273f6786f83311e87e1fa6f1a04
    host: localhost

# Max elements quantity per pagination.
maxElementsPerPagination: 20