port: 8080
logsFile: logs/server.log

database:
    port: 5432
    name: beppin
    user: beppin
    password: b26edb839ea81fe0801f9d47f17aaeaac2e1162fe28a3487f51a3ee7716d1ef7
    host: localhost
    sslmode: require

secretKey: 60129972d1d3655498d9bf649e04c823d06dcab7efd41cf6c93a6f4b656d867c

# Max elements quantity per pagination.
maxElementsPerPagination: 20